apiVersion: apps/v1
kind: Deployment
metadata:
  name: party-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: party-service
  template:
    metadata:
      labels:
        app: party-service
    spec:
      containers:
        - name: party-service
          image: party-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          # --- SECTION CRUCIALE POUR EUREKA ---
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_CLOUD_COMPATIBILITY-VERIFIER_ENABLED
              value: "false"
          # ------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: party-service
spec:
  selector:
    app: party-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort