apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-service
          image: stats-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          # --- CONFIGURATION EUREKA & COMPATIBILITÉ ---
          env:
            - name: SPRING_CLOUD_COMPATIBILITY-VERIFIER_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          # --------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
spec:
  selector:
    app: stats-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort