server:
  port: 8083

spring:
  application:
    name: stats-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

services:
  party-url: http://party-service:8081
  player-url: http://player-service:8082

resilience4j:
  circuitbreaker:
    instances:
      playerService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      playerService:
        max-attempts: 3
        wait-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true