server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # Le serveur ne s'enregistre pas lui-même
    register-with-eureka: false
    fetch-registry: false
  instance:
    # Aide Prometheus à identifier l'instance par son IP dans le cluster
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  # Nouvelle syntaxe Spring Boot 3.x pour éviter le message 'Deprecated'
  prometheus:
    metrics:
      export:
        enabled: true